### ISSUE TITLE
launcher seems to ignore my VerticleFactory

### ISSUE THREAD

**Issue by bitkid** [eclipse-vertx/vertx-launcher#11]
i overwrite a method in VertxApplicationHooks

override fun afterVertxStarted(context: HookContext) {
     context.vertx().registerVerticleFactory(MyFactory())
}

i package everything and run my command line like this

java -jar db-syncer/build/libs/db-syncer-all.jar com.scinteco.repong.dbsync.DbSyncerDeploymentVerticle

the stacktrace:

2024-10-11 15:53:26.154 [main] ERROR i.v.l.application.VertxApplication - Failed in deploying verticle
java.lang.NoSuchMethodException: com.scinteco.repong.dbsync.DbSyncerDeploymentVerticle.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3761)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930)
        at io.vertx.core.impl.verticle.JavaVerticleFactory.lambda$createVerticle2$0(JavaVerticleFactory.java:47)
        at io.vertx.core.impl.deployment.Deployment.deployment(Deployment.java:39)
        at io.vertx.core.impl.verticle.VerticleManager.deployVerticle(VerticleManager.java:221)
        at io.vertx.core.impl.verticle.VerticleManager.lambda$deployVerticle$3(VerticleManager.java:210)

i think it should not end up in JavaVerticleFactory but in my own factory or?
also, DbSyncerDeploymentVerticle extends CoroutineVerticle, so it should have a init() method

**Comment by tsegismont** [comment]
Can you share a minimal reproducer on GH please?

**Comment by bitkid** [comment]
https://gist.github.com/bitkid/a8d08d4fd7bb99cd4519f34f5f454d55

**Comment by bitkid** [comment]
so the DeploymentVerticle is called .. but when i try to do vertx.deployVerticle("bla.TestVerticle") .. it's not using the registered factory but the JavaVerticleFactory instead

**Comment by bitkid** [comment]
nvm .. seems to be my problem

**Comment by tsegismont** [comment]
Thanks for letting us know.
