### ISSUE TITLE
Current 5.0.0-SNAPHOST (2023-10-28) references deployment option isWorker which was recently removed

### ISSUE THREAD

**Issue by apatrida** [eclipse-vertx/vertx-launcher#4]
### Version

5.0.0-SNAPSHOT as-of 2023-10-28

### Context

Current code throws an exception when using launcher because it references a non-existent method:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean io.vertx.core.DeploymentOptions.isWorker()'
	at io.vertx.launcher.application.impl.VertxApplicationCommand.run(VertxApplicationCommand.java:216)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.vertx.launcher.application.VertxApplication.launch(VertxApplication.java:99)
	...
```

Opening this project, also shows this as a current error in the code:

<img width="1209" alt="Screenshot 2023-10-28 at 12 23 36 PM" src="https://github.com/eclipse-vertx/vertx-launcher/assets/182340/92d6cb38-4046-44c5-9033-38f11ae81904">

**Comment by apatrida** [comment]
Change 5f272809 from @vietj in core is the issue:
https://github.com/eclipse-vertx/vert.x/commit/c4979a0c37225397cccdb45346b8e46fca4082db

I think the threading model is now the only detection mechanism.

**Comment by apatrida** [comment]
It's probably that the `-w, -worker, --worker` options no longer make sense here as you can select three options now, using event-loop (normal verticle), worker, or virtual thread.

**Comment by vietj** [comment]
the bug has been fixed but we certainly need to take an action here

**Comment by tsegismont** [comment]
I think we don't need to get rid of the worker flag. Instead, we can:

- add a new flag for virtual thread deployment
- fail deployment if both the worker and virtual thread deployment flags are set.

I see the following advantages:

- deploying with VT model only requires a flag
- no breaking change for existing applications
